
export const testData = {
    sequence: "NNCB",
    changes: [
        { from: "CH", to: "B" },
        { from: "HH", to: "N" },
        { from: "CB", to: "H" },
        { from: "NH", to: "C" },
        { from: "HB", to: "C" },
        { from: "HC", to: "B" },
        { from: "HN", to: "C" },
        { from: "NN", to: "C" },
        { from: "BH", to: "H" },
        { from: "NC", to: "B" },
        { from: "NB", to: "B" },
        { from: "BN", to: "B" },
        { from: "BB", to: "N" },
        { from: "BC", to: "B" },
        { from: "CC", to: "N" },
        { from: "CN", to: "C" },
    ]
}

export const data = {
    sequence: "NBOKHVHOSVKSSBSVVBCS",
    changes: [
        { from: "SN", to: "H" },
        { from: "KP", to: "O" },
        { from: "CP", to: "V" },
        { from: "FN", to: "P" },
        { from: "FV", to: "S" },
        { from: "HO", to: "S" },
        { from: "NS", to: "N" },
        { from: "OP", to: "C" },
        { from: "HC", to: "S" },
        { from: "NP", to: "B" },
        { from: "CF", to: "V" },
        { from: "NN", to: "O" },
        { from: "OS", to: "F" },
        { from: "VO", to: "V" },
        { from: "HK", to: "N" },
        { from: "SV", to: "V" },
        { from: "VC", to: "V" },
        { from: "PH", to: "K" },
        { from: "NH", to: "O" },
        { from: "SB", to: "N" },
        { from: "KS", to: "V" },
        { from: "CB", to: "H" },
        { from: "SS", to: "P" },
        { from: "SP", to: "H" },
        { from: "VN", to: "K" },
        { from: "VP", to: "O" },
        { from: "SK", to: "V" },
        { from: "VF", to: "C" },
        { from: "VV", to: "B" },
        { from: "SF", to: "K" },
        { from: "HH", to: "K" },
        { from: "PV", to: "V" },
        { from: "SO", to: "H" },
        { from: "NK", to: "P" },
        { from: "NO", to: "C" },
        { from: "ON", to: "S" },
        { from: "PB", to: "K" },
        { from: "VS", to: "H" },
        { from: "SC", to: "P" },
        { from: "HS", to: "P" },
        { from: "BS", to: "P" },
        { from: "CS", to: "P" },
        { from: "VB", to: "V" },
        { from: "BP", to: "K" },
        { from: "FH", to: "O" },
        { from: "OF", to: "F" },
        { from: "HF", to: "F" },
        { from: "FS", to: "C" },
        { from: "BN", to: "O" },
        { from: "NC", to: "F" },
        { from: "FC", to: "B" },
        { from: "CV", to: "V" },
        { from: "HN", to: "C" },
        { from: "KF", to: "K" },
        { from: "OO", to: "P" },
        { from: "CC", to: "S" },
        { from: "FF", to: "C" },
        { from: "BC", to: "P" },
        { from: "PP", to: "F" },
        { from: "KO", to: "V" },
        { from: "PC", to: "B" },
        { from: "HB", to: "H" },
        { from: "OB", to: "N" },
        { from: "OV", to: "S" },
        { from: "KH", to: "B" },
        { from: "BO", to: "B" },
        { from: "HV", to: "P" },
        { from: "BV", to: "K" },
        { from: "PS", to: "F" },
        { from: "CH", to: "C" },
        { from: "SH", to: "H" },
        { from: "OK", to: "V" },
        { from: "NB", to: "K" },
        { from: "BF", to: "S" },
        { from: "CO", to: "O" },
        { from: "NV", to: "H" },
        { from: "FB", to: "K" },
        { from: "FO", to: "C" },
        { from: "CK", to: "P" },
        { from: "BH", to: "B" },
        { from: "OH", to: "F" },
        { from: "KB", to: "N" },
        { from: "OC", to: "K" },
        { from: "KK", to: "O" },
        { from: "CN", to: "H" },
        { from: "FP", to: "K" },
        { from: "VH", to: "K" },
        { from: "VK", to: "P" },
        { from: "HP", to: "S" },
        { from: "FK", to: "F" },
        { from: "BK", to: "H" },
        { from: "KV", to: "V" },
        { from: "BB", to: "O" },
        { from: "KC", to: "F" },
        { from: "KN", to: "C" },
        { from: "PO", to: "P" },
        { from: "NF", to: "P" },
        { from: "PN", to: "S" },
        { from: "PF", to: "S" },
        { from: "PK", to: "O" },
    ],
}
