
export const testData1 = [
    {from: "start", to: "A"},
    {from: "start", to: "b"},
    {from: "A", to: "c"},
    {from: "A", to: "b"},
    {from: "b", to: "d"},
    {from: "A", to: "end"},
    {from: "b", to: "end"},
]

export const testData2 = [
    {from: "dc", to: "end"},
    {from: "HN", to: "start"},
    {from: "start", to: "kj"},
    {from: "dc", to: "start"},
    {from: "dc", to: "HN"},
    {from: "LN", to: "dc"},
    {from: "HN", to: "end"},
    {from: "kj", to: "sa"},
    {from: "kj", to: "HN"},
    {from: "kj", to: "dc"},
]

export const testData3 = [
    {from: "fs", to: "end"},
    {from: "he", to: "DX"},
    {from: "fs", to: "he"},
    {from: "start", to: "DX"},
    {from: "pj", to: "DX"},
    {from: "end", to: "zg"},
    {from: "zg", to: "sl"},
    {from: "zg", to: "pj"},
    {from: "pj", to: "he"},
    {from: "RW", to: "he"},
    {from: "fs", to: "DX"},
    {from: "pj", to: "RW"},
    {from: "zg", to: "RW"},
    {from: "start", to: "pj"},
    {from: "he", to: "WI"},
    {from: "zg", to: "he"},
    {from: "pj", to: "fs"},
    {from: "start", to: "RW"},
]

export const data = [
    {from: "xz", to: "end"},
    {from: "CJ", to: "pt"},
    {from: "pt", to: "QW"},
    {from: "hn", to: "SP"},
    {from: "pw", to: "CJ"},
    {from: "SP", to: "end"},
    {from: "hn", to: "pt"},
    {from: "GK", to: "nj"},
    {from: "fe", to: "nj"},
    {from: "CJ", to: "nj"},
    {from: "hn", to: "ZZ"},
    {from: "hn", to: "start"},
    {from: "hn", to: "fe"},
    {from: "ZZ", to: "fe"},
    {from: "SP", to: "nj"},
    {from: "SP", to: "xz"},
    {from: "ZZ", to: "pt"},
    {from: "nj", to: "ZZ"},
    {from: "start", to: "ZZ"},
    {from: "hn", to: "GK"},
    {from: "CJ", to: "end"},
    {from: "start", to: "fe"},
    {from: "CJ", to: "xz"},
]
